import Navbar from '@/components/layout/Navbar'
import Footer from '@/components/layout/Footer'
import Rule from '@/components/ui/Rule'

export const metadata = {
  title: 'Privacy Policy — ekai',
}

export default function PrivacyPolicy() {
  return (
    <>
      <Navbar />
      <main className="bg-cream pt-[60px]">
        <div className="max-w-[760px] mx-auto px-6 md:px-12 py-20">
          <p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-muted mb-4">Legal</p>
          <h1 className="font-black text-ink tracking-[-0.035em] leading-[1.05] mb-4" style={{ fontSize: 'clamp(32px, 4vw, 52px)' }}>
            Privacy Policy
          </h1>
          <p className="text-muted text-[14px] mb-16">Last updated: February 04, 2026</p>

          <Rule />

          <div className="mt-16 flex flex-col gap-6">

            <p className="text-muted text-[15px] leading-relaxed">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>

            <Section title="Interpretation and Definitions">
              <P>The words of which the initial letter is capitalised have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</P>
              <ul className="flex flex-col gap-2 pl-4 mt-2">
                {[
                  'Account means a unique account created for You to access our Service or parts of our Service.',
                  'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
                  'Application refers to ekai, the software program provided by the Company.',
                  'Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to IDX Studios Inc., 38 Smithe Street, Vancouver, BC, Canada.',
                  'Country refers to: British Columbia, Canada.',
                  'Device means any device that can access the Service such as a computer, a cell phone or a digital tablet.',
                  'Personal Data is any information that relates to an identified or identifiable individual.',
                  'Service refers to the Application.',
                  'Service Provider means any natural or legal person who processes the data on behalf of the Company.',
                  'Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.',
                  'You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
                ].map((item, i) => (
                  <li key={i} className="flex items-start gap-2 text-muted text-[14px] leading-relaxed">
                    <span className="w-1 h-1 rounded-full bg-orange flex-shrink-0 mt-[9px]" />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </Section>

            <Section title="Collecting and Using Your Personal Data">
              <h3 className="font-semibold text-ink text-[15px] mt-2">Types of Data Collected</h3>
              <P>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: email address, first name and last name, and Usage Data.</P>
              <h3 className="font-semibold text-ink text-[15px] mt-2">Usage Data</h3>
              <P>Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</P>
            </Section>

            <Section title="Use of Google Workspace Data">
              <h3 className="font-semibold text-ink text-[15px] mt-2">Data Usage for AI/ML Models</h3>
              <ul className="flex flex-col gap-2 pl-4 mt-1">
                <li className="flex items-start gap-2 text-muted text-[14px] leading-relaxed"><span className="w-1 h-1 rounded-full bg-orange flex-shrink-0 mt-[9px]" /><span>Our app <strong className="text-ink">does not use Google Workspace data to develop, improve, or train generalized/non-personalized AI and/or ML models</strong>.</span></li>
                <li className="flex items-start gap-2 text-muted text-[14px] leading-relaxed"><span className="w-1 h-1 rounded-full bg-orange flex-shrink-0 mt-[9px]" /><span>If our app uses Google Workspace data, it is solely for the purpose of training personalized AI/ML models to enhance user-specific experiences.</span></li>
              </ul>
              <h3 className="font-semibold text-ink text-[15px] mt-4">Data Transfer to Third-Party AI Tools</h3>
              <ul className="flex flex-col gap-2 pl-4 mt-1">
                <li className="flex items-start gap-2 text-muted text-[14px] leading-relaxed"><span className="w-1 h-1 rounded-full bg-orange flex-shrink-0 mt-[9px]" /><span>Our app <strong className="text-ink">does not transfer Google Workspace data to third-party AI tools for the purpose of developing, improving, or training generalized/non-personalized AI/ML models</strong>.</span></li>
                <li className="flex items-start gap-2 text-muted text-[14px] leading-relaxed"><span className="w-1 h-1 rounded-full bg-orange flex-shrink-0 mt-[9px]" /><span>Any transfer of Google Workspace data to third-party AI tools is strictly for personalized AI/ML model training, aimed at improving individual user experiences.</span></li>
              </ul>
              <h3 className="font-semibold text-ink text-[15px] mt-4">Data Security and Privacy</h3>
              <P>We implement robust security measures to protect your data from unauthorized access, disclosure, alteration, or destruction. Our privacy policy outlines our data security practices and the steps we take to ensure the confidentiality and integrity of your data.</P>
            </Section>

            <Section title="Use of Your Personal Data">
              <P>The Company may use Personal Data for the following purposes: to provide and maintain our Service; to manage Your Account; for the performance of a contract; to contact You regarding updates or informative communications; to provide You with news and special offers; to manage Your requests; for business transfers; and for other purposes such as data analysis, identifying usage trends, and improving our Service.</P>
              <P>We may share Your personal information with Service Providers, for business transfers, with Affiliates, with business partners, with other users where you interact publicly, and with Your consent.</P>
            </Section>

            <Section title="Retention of Your Personal Data">
              <P>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</P>
            </Section>

            <Section title="Transfer of Your Personal Data">
              <P>Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organisation or a country unless there are adequate controls in place.</P>
            </Section>

            <Section title="Data Deletion, Access, and Transfer Requests">
              <h3 className="font-semibold text-ink text-[15px] mt-2">Request to Delete Your Data</h3>
              <P>If you would like to delete your data, send an email to <a href="mailto:hello@yourekai.com" className="text-orange underline">hello@yourekai.com</a> with the subject line &ldquo;Data Deletion Request,&rdquo; or navigate to &ldquo;Account Settings&rdquo; &gt; &ldquo;Privacy Settings&rdquo; and submit a deletion request. We will verify your identity and process the deletion within 30 days.</P>
              <h3 className="font-semibold text-ink text-[15px] mt-4">Request to Access Your Data</h3>
              <P>Send an email to <a href="mailto:hello@yourekai.com" className="text-orange underline">hello@yourekai.com</a> with the subject line &ldquo;Data Access Request.&rdquo; We will provide a copy of your data in a structured, commonly used, and machine-readable format.</P>
              <h3 className="font-semibold text-ink text-[15px] mt-4">Request to Transfer Your Data</h3>
              <P>Email us at <a href="mailto:hello@yourekai.com" className="text-orange underline">hello@yourekai.com</a> with the subject line &ldquo;Data Transfer Request.&rdquo; Specify the destination service and format preferences, and we will assist with the secure transfer of your data.</P>
            </Section>

            <Section title="Disclosure of Your Personal Data">
              <P>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</P>
              <P>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities. The Company may also disclose Your Personal Data to comply with a legal obligation, protect the rights or property of the Company, prevent possible wrongdoing, or protect against legal liability.</P>
            </Section>

            <Section title="Security of Your Personal Data">
              <P>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</P>
            </Section>

            <Section title="Children's Privacy">
              <P>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</P>
            </Section>

            <Section title="Changes to this Privacy Policy">
              <P>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective.</P>
            </Section>

            <Section title="Contact Us">
              <P>If you have any questions about this Privacy Policy, you can contact us by email at <a href="mailto:hello@yourekai.com" className="text-orange underline">hello@yourekai.com</a>.</P>
            </Section>

          </div>
        </div>
      </main>
      <Footer />
    </>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-3 pt-4">
      <h2 className="font-bold text-ink text-[18px] tracking-[-0.02em]">{title}</h2>
      {children}
    </div>
  )
}

function P({ children }: { children: React.ReactNode }) {
  return <p className="text-muted text-[14px] leading-[1.75]">{children}</p>
}
